// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txuiccbuksmdcqsksefl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4dWljY2J1a3NtZGNxc2tzZWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjE5MjgsImV4cCI6MjA2MDIzNzkyOH0.S-Yf2gB8Zb3yKKuytQhKr3UXfkSWRys5UFmxHWqYYpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);